export const birthdays = [
  {
    name: "Alex",
    surname: "White",
    day: 7,
    month: "Jan",
    favorite: true,
    note: "noob",
  },
  {
    name: "Emma",
    surname: "White",
    day: 8,
    month: "Jan",
    favorite: false,
    note: "your note",
  },
  {
    name: "Charlotte",
    surname: "White",
    day: 2,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Amelia",
    surname: "White",
    day: 3,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Sophia",
    surname: "White",
    day: 4,
    month: 1,
    favorite: true,
    note: "your note",
  },
  {
    name: "Isabella",
    surname: "White",
    day: 4,
    month: 11,
    favorite: true,
    note: "your note",
  },
  {
    name: "Ava",
    surname: "White",
    day: 5,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Mia",
    surname: "White",
    day: 6,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Evelyn",
    surname: "White",
    day: 7,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Luna",
    surname: "White",
    day: 8,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Harper",
    surname: "White",
    day: 9,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Camila",
    surname: "White",
    day: 10,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Sofia",
    surname: "White",
    day: 11,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Scarlett",
    surname: "White",
    day: 12,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Elizabeth",
    surname: "White",
    day: 13,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Eleanor",
    surname: "White",
    day: 14,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Emily",
    surname: "White",
    day: 15,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Chloe",
    surname: "White",
    day: 16,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Mila",
    surname: "White",
    day: 17,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Violet",
    surname: "White",
    day: 18,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Penelope",
    surname: "White",
    day: 19,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Gianna",
    surname: "White",
    day: 20,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Aria",
    surname: "White",
    day: 21,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Abigail",
    surname: "White",
    day: 22,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Ella",
    surname: "White",
    day: 23,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Avery",
    surname: "White",
    day: 24,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Hazel",
    surname: "White",
    day: 25,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Nora",
    surname: "White",
    day: 26,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Layla",
    surname: "White",
    day: 27,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Lily",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Aurora",
    surname: "White",
    day: 29,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Nova",
    surname: "White",
    day: 30,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Ellie",
    surname: "White",
    day: 31,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Madison",
    surname: "White",
    day: 1,
    month: 1,
    favorite: false,
    note: "your note",
  },
  {
    name: "Grace",
    surname: "White",
    day: 2,
    month: 1,
    favorite: false,
    note: "your note",
  },
  {
    name: "Isla",
    surname: "White",
    day: 3,
    month: 1,
    favorite: false,
    note: "your note",
  },
  {
    name: "Willow",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Zoe",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Riley",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Stella",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Eliana",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Ivy",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Victoria",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Emilia",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Zoey",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Naomi",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Hannah",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Lucy",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Elena",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    name: "Lillian",
    surname: "White",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
];
