export const birthdays = [
  {
    id: 0,
    name: "Саня",
    surname: "Дуло",
    username: "Генерал Токсин",
    day: 28,
    month: 10,
    favorite: true,
    note: "noob",
  },
  {
    id: 1,
    name: "Emma",
    surname: "White",
    username: "wellwellwell",
    day: 10,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 2,
    name: "Charlotte",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 10,
    favorite: true,
    note: "your note",
  },
  {
    id: 3,
    name: "Amelia",
    surname: "White",
    username: "wellwellwell",
    day: 29,
    month: 10,
    favorite: false,
    note: "your note",
  },
  {
    id: 4,
    name: "Sophia",
    surname: "White",
    username: "wellwellwell",
    day: 30,
    month: 10,
    favorite: false,
    note: "your note",
  },
  {
    id: 5,
    name: "Isabella",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 1,
  },
  {
    id: 6,
    name: "Ava",
    surname: "White",
    username: "wellwellwell",
    day: 25,
    month: 10,
    favorite: false,
    note: "your note",
  },
  {
    id: 7,
    name: "Mia",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 8,
    name: "Evelyn",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 9,
    name: "Luna",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 10,
    name: "Harper",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 11,
    name: "Camila",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 12,
    name: "Sofia",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 13,
    name: "Scarlett",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 14,
    name: "Elizabeth",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 15,
    name: "Eleanor",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 16,
    name: "Emily",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 17,
    name: "Chloe",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 18,
    name: "Mila",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 19,
    name: "Violet",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 20,
    name: "Penelope",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 21,
    name: "Gianna",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 22,
    name: "Aria",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 23,
    name: "Abigail",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 24,
    name: "Ella",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 25,
    name: "Avery",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 26,
    name: "Hazel",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 27,
    name: "Nora",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 28,
    name: "Layla",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 29,
    name: "Lily",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 30,
    name: "Aurora",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 31,
    name: "Nova",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 32,
    name: "Ellie",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 33,
    name: "Madison",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 34,
    name: "Grace",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 35,
    name: "Isla",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 36,
    name: "Willow",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 37,
    name: "Zoe",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 38,
    name: "Riley",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 39,
    name: "Stella",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 40,
    name: "Eliana",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 41,
    name: "Ivy",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 42,
    name: "Victoria",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 43,
    name: "Emilia",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 44,
    name: "Zoey",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 45,
    name: "Naomi",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 46,
    name: "Hannah",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 47,
    name: "Lucy",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 48,
    name: "Elena",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
  {
    id: 49,
    name: "Lillian",
    surname: "White",
    username: "wellwellwell",
    day: 28,
    month: 11,
    favorite: false,
    note: "your note",
  },
];
